### ISSUE TITLE
No data on my page

### ISSUE THREAD

**Issue by pippo73** [mak08/VRDashboard#17]
I have intalled your plugin on a chrome istance.
1) I connect to VR page ad I login.
2) after that I click the RED "Z" to activate the plugin.
3) it opens a new page, but it does not loads or update any data?

what could it be?

**Comment by mak08** [comment]
Before reporting an issue, please 
- check the user manual (linked in VR Dashboard, also available [here](http://bitweide.de/vrdashboard/manual.html)
- check the [Chrome web store](https://chrome.google.com/webstore/detail/vr-dashboard/amknkhejaogpekncjekiaolgldbejjan) support page
- chek if the issue was already discussed on the [router forum](http://zezo.org/forum.pl)
Thanks!
