### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by LeonCitrone** [mak08/VRDashboard#46]
Hi
The dashboard is not working since VR did some updates yesterday.
Is it possible to check? We are a several amount of players using yours and not the one who stole your work.
Thank you Hardtack

**Comment by mcmgj** [comment]
Hi 

update your version to 1.2.0 if not 



----- Mail original -----

De: "LeonCitrone" ***@***.***> 
À: "mak08/VRDashboard" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Jeudi 26 Octobre 2023 10:11:51 
Objet: [mak08/VRDashboard] Dashboard not working (Issue #46) 



Hi 
The dashboard is not working since VR did some updates yesterday. 
Is it possible to check? We are a several amount of players using yours and not the one who stole your work. 
Thank you Hardtack

**Comment by LeonCitrone** [comment]
???
The latest version is 4.21.2

**Comment by mcmgj** [comment]
USE ITYC VRDASHBOARD instead ... Chrome extension 



----- Mail original -----

De: "LeonCitrone" ***@***.***> 
À: "mak08/VRDashboard" ***@***.***> 
Cc: "mcmgj" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Jeudi 26 Octobre 2023 14:30:22 
Objet: Re: [mak08/VRDashboard] Dashboard not working (Issue #46) 



??? 
The latest version is 4.21.2

**Comment by toxcct** [comment]
> USE ITYC VRDASHBOARD instead ... Chrome extension

Irrelevant answer, this is the `mak08/VRDashbaord` repository ! 😨

**Comment by LeonCitrone** [comment]
> USE ITYC VRDASHBOARD instead ... Chrome extension
> […](#)
> ----- Mail original ----- De: "LeonCitrone" ***@***.***> À: "mak08/VRDashboard" ***@***.***> Cc: "mcmgj" ***@***.***>, "Comment" ***@***.***> Envoyé: Jeudi 26 Octobre 2023 14:30:22 Objet: Re: [mak08/VRDashboard] Dashboard not working (Issue #46) ??? The latest version is 4.21.2 — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: <mak08/VRDashboard/issues/46/1781027604 @ github . com>

I don't give a shit about ityc, i don't like stealers and people who are using people's data for sending to his own servers.
And it's Hardtacks github, so, go far, far away.

**Comment by mcmgj** [comment]
please send me your comments 

----- Mail original -----

De: "LeonCitrone" ***@***.***> 
À: "mak08/VRDashboard" ***@***.***> 
Cc: "mcmgj" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Jeudi 26 Octobre 2023 14:30:22 
Objet: Re: [mak08/VRDashboard] Dashboard not working (Issue #46) 



??? 
The latest version is 4.21.2

**Comment by mcmgj** [comment]
If you see help infomations of VRdashboard on hardtracks, you can see my name (mcmgj). 
ITYC dashboard is a brach of Hardtrack/mark08. 

If you don't send your data, you can select no send on parameters... 

The datas collected are only the race data to update quickly the form 
The sources is on github and free to use ... 

So you can pickup the update to adapt Hardtrack ! 



----- Mail original -----

De: "LeonCitrone" ***@***.***> 
À: "mak08/VRDashboard" ***@***.***> 
Cc: "mcmgj" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Jeudi 26 Octobre 2023 15:13:05 
Objet: Re: [mak08/VRDashboard] Dashboard not working (Issue #46) 





USE ITYC VRDASHBOARD instead ... Chrome extension 
… 
----- Mail original ----- De: "LeonCitrone" @ . > À: "mak08/VRDashboard" @ . > Cc: "mcmgj" @ . >, "Comment" @ . > Envoyé: Jeudi 26 Octobre 2023 14:30:22 Objet: Re: [mak08/VRDashboard] Dashboard not working (Issue #46 ) ??? The latest version is 4.21.2 — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: < /issues/46 /1781027604 @ github . com> 


I don't give a shit about ityc, i don't like stealers and people who are using people's data for sending to his own servers. 
And it's Hardtacks github, so, go far, far away.

**Comment by mcmgj** [comment]
sorry if my suggestion was inappropriate,
it is possible to have the 2 versions coexist on your browser and compare them, ITYC is the initial dashboard of Mark08 redeveloped, with various improvements over time

**Comment by 7killer** [comment]
> > USE ITYC VRDASHBOARD instead ... Chrome extension
> > […](#)
> > ----- Mail original ----- De: "LeonCitrone" _**@**_._**> À: "mak08/VRDashboard" _**@**_.**_> Cc: "mcmgj" _**@**_._**>, "Comment" _**@**_.**_> Envoyé: Jeudi 26 Octobre 2023 14:30:22 Objet: Re: [mak08/VRDashboard] Dashboard not working (Issue #46) ??? The latest version is 4.21.2 — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: <[/issues/46](https://github.com/mak08/VRDashboard/issues/46)/1781027604 @ github . com>
> 
> I don't give a shit about ityc, i don't like stealers and people who are using people's data for sending to his own servers. And it's Hardtacks github, so, go far, far away.

If i was the guy , you seems think i m, i ll never take the time to purpose a pullrequest to fix the current situation.

You looking suspect me to do some stuffs , i ll be happy to clarify the situation, feel free to contact me on discord

**Comment by mak08** [comment]
> Hi The dashboard is not working since VR did some updates yesterday. Is it possible to check? We are a several amount of players using yours and not the one who stole your work. Thank you Hardtack

Thanks for sticking with the original :-) 
I didn't look at the repo a lot recently, but this issue is now fixed.
